services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      TZ: 'Asia/Tokyo'
    cap_add:
      - SYS_NICE  
    volumes:
      - ./db.mysql:/var/lib/mysql
    env_file:
      - .env.development
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    # command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/src:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.development
    tty: true
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/app:/app
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true
volumes:
  node_modules:
  local_info:
