services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      TZ: 'Asia/Tokyo'
    cap_add:
      - SYS_NICE  
    volumes:
      - ./db.mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env.development
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/app:/app
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    volumes:
      - ./backend/code:/code
    stdin_open: true
    tty: true
    env_file:
      - .env.development
volumes:
  node_modules:
  local_info:
